<?php
require_once __DIR__ . "/../Database/session-checker.php";
require_once __DIR__ . "/../Database/connection.php";

// 🔹 Handle create masterlist form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['create_masterlist'])) {
    $term = $_POST['term'];
    $year = $_POST['year'];
    $program = $_POST['program'];
    $section = $_POST['section'];
    $generated_by = $_SESSION['user_id'];

    $stmt = $conn->prepare("INSERT INTO masterlists (term, year, program, section, generated_by) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("ssssi", $term, $year, $program, $section, $generated_by);
    $stmt->execute();

    echo "<script>alert('Masterlist created successfully!');</script>";
}

// 🔹 Fetch all masterlists
$sql = "SELECT m.masterlist_id, m.term, m.year, m.program, m.section, m.generation_date, u.username 
        FROM masterlists m
        LEFT JOIN users u ON m.generated_by = u.user_id
        ORDER BY m.generation_date DESC";
$result = $conn->query($sql);
$masterlists = $result->fetch_all(MYSQLI_ASSOC);

// 🔹 If "view_students" is triggered
$students_in_masterlist = [];
$viewing_masterlist = null;

if (isset($_GET['view_students'])) {
    $viewing_masterlist = intval($_GET['view_students']);
    $stmt = $conn->prepare("
        SELECT s.student_id, s.first_name, s.last_name, s.program, s.year_level, s.student_status, m.section
        FROM masterlist_details md
        JOIN students s ON md.student_id = s.student_id
        JOIN masterlists m ON md.masterlist_id = m.masterlist_id
        WHERE md.masterlist_id = ?
    ");
    $stmt->bind_param("i", $viewing_masterlist);
    $stmt->execute();
    $students_in_masterlist = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Masterlist</title>
  <link rel="stylesheet" href="../components/css/masterlists.css">
</head>
<body>

<?php include 'StaffSidenav.php'; ?>

<div class="container">
  <h1>📑 Masterlist Manager</h1>
  <p>Create, view, and export student masterlists per term, year, program, and section.</p>

  <!-- ➕ Create Masterlist -->
  <div class="actions">
    <button class="primary" onclick="openCreateModal()">+ Create New Masterlist</button>
  </div>

  <!-- 📄 Masterlist Table -->
  <div class="card">
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Term</th>
          <th>Year</th>
          <th>Program</th>
          <th>Section</th>
          <th>Generated By</th>
          <th>Date</th>
          <th style="width:220px;">Actions</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($masterlists as $m): ?>
        <tr>
          <td><?= $m['masterlist_id'] ?></td>
          <td><?= htmlspecialchars($m['term']) ?></td>
          <td><?= htmlspecialchars($m['year']) ?></td>
          <td><?= htmlspecialchars($m['program']) ?></td>
          <td><?= htmlspecialchars($m['section']) ?></td>
          <td><?= htmlspecialchars($m['username']) ?></td>
          <td><?= $m['generation_date'] ?></td>
          <td>
            <a href="?view_students=<?= $m['masterlist_id'] ?>"><button>👀 View</button></a>
            <button>⬇ Export</button>
            <button class="danger">🗑 Delete</button>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>

<!-- Create Masterlist Modal -->
<div id="createModal" class="modal">
  <div class="modal-content">
    <span class="close" onclick="closeCreateModal()">&times;</span>
    <h2>Create New Masterlist</h2>
    <form method="POST">
      <label>Term</label>
      <select name="term" required>
        <option value="1st Sem">1st Sem</option>
        <option value="2nd Sem">2nd Sem</option>
        <option value="Summer">Summer</option>
      </select>

      <label>Year</label>
      <input type="text" name="year" value="2025-2026" required>

      <label>Program</label>
      <select name="program" required>
        <option value="BSIT">BSIT</option>
        <option value="BSA">BSA</option>
        <option value="BSBA">BSBA</option>
      </select>

      <label>Section</label>
      <input type="text" name="section" placeholder="e.g. 2201" required>

      <div class="form-actions">
        <button type="button" class="secondary" onclick="closeCreateModal()">Cancel</button>
        <button type="submit" class="primary" name="create_masterlist">Generate</button>
      </div>
    </form>
  </div>
</div>

<!-- Students in Masterlist Modal -->
<?php if ($viewing_masterlist): ?>
<div id="studentsModal" class="modal" style="display:flex;">
  <div class="modal-content wide">
    <a href="Masterlist.php" class="close">&times;</a>
    <h2>👩‍🎓 Students in Masterlist (ID: <?= $viewing_masterlist ?>)</h2>
    <table>
      <thead>
        <tr>
          <th>Student ID</th>
          <th>Name</th>
          <th>Program</th>
          <th>Year Level</th>
          <th>Section</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <?php if ($students_in_masterlist): ?>
          <?php foreach ($students_in_masterlist as $s): ?>
          <tr>
            <td><?= $s['student_id'] ?></td>
            <td><?= htmlspecialchars($s['first_name'] . " " . $s['last_name']) ?></td>
            <td><?= htmlspecialchars($s['program']) ?></td>
            <td><?= htmlspecialchars($s['year_level']) ?></td>
            <td><?= htmlspecialchars($s['section']) ?></td>
            <td><?= htmlspecialchars($s['student_status']) ?></td>
          </tr>
          <?php endforeach; ?>
        <?php else: ?>
          <tr><td colspan="6">No students in this masterlist yet.</td></tr>
        <?php endif; ?>
      </tbody>
    </table>
  </div>
</div>
<?php endif; ?>

<script>
function openCreateModal() { document.getElementById("createModal").style.display = "flex"; }
function closeCreateModal() { document.getElementById("createModal").style.display = "none"; }
</script>

</body>
</html>
