<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Masterlist</title>
  <link rel="stylesheet" href="../components/css/masterlists.css">
</head>
<body>

<?php include 'StaffSidenav.php'; ?>

<div class="container">
  <h1>Masterlist Section</h1>
  <p>Manage and view generated student masterlists.</p>

  <!-- ➕ Create Masterlist -->
  <div class="actions">
    <button onclick="openCreateModal()">+ Create New Masterlist</button>
  </div>

  <!-- 📄 Masterlist Table -->
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Term</th>
        <th>Year</th>
        <th>Program</th>
        <th>Generated By</th>
        <th>Date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <!-- Example row -->
      <tr>
        <td>1</td>
        <td>1st Sem</td>
        <td>2025-2026</td>
        <td>BSIT</td>
        <td>Registrar Staff</td>
        <td>2025-09-29</td>
        <td>
          <button onclick="openStudentsModal()">View Students</button>
          <button>Export</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<!-- Create Masterlist Modal -->
<div id="createModal" class="modal">
  <div class="modal-content">
    <span class="close" onclick="closeCreateModal()">&times;</span>
    <h2>Create New Masterlist</h2>
    <form>
      <label>Term</label>
      <input type="text" placeholder="e.g. 1st Sem">
      <label>Year</label>
      <input type="text" placeholder="e.g. 2025-2026">
      <label>Program</label>
      <input type="text" placeholder="e.g. BSIT">
      <button type="submit">Generate</button>
    </form>
  </div>
</div>

<!-- Students in Masterlist Modal -->
<div id="studentsModal" class="modal">
  <div class="modal-content" style="width:700px;">
    <span class="close" onclick="closeStudentsModal()">&times;</span>
    <h2>Students in Masterlist</h2>
    <table>
      <thead>
        <tr>
          <th>Student ID</th>
          <th>Name</th>
          <th>Program</th>
          <th>Year Level</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>S2025-001</td>
          <td>Juan Dela Cruz</td>
          <td>BSIT</td>
          <td>1</td>
          <td>Enrolled</td>
        </tr>
        <tr>
          <td>S2025-002</td>
          <td>Maria Santos</td>
          <td>BSA</td>
          <td>2</td>
          <td>Enrolled</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<script>
function openCreateModal() {
  document.getElementById("createModal").style.display = "flex";
}
function closeCreateModal() {
  document.getElementById("createModal").style.display = "none";
}
function openStudentsModal() {
  document.getElementById("studentsModal").style.display = "flex";
}
function closeStudentsModal() {
  document.getElementById("studentsModal").style.display = "none";
}
</script>

</body>
</html>
